import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Sidebar from '../components/Sidebar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WhatsApp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/whatsapp.png" type="image/x-icon" />
      </Head>

      <Sidebar />
    </div>
  )
}

export default Home
